const PAIRS: [string, string][] = [
  ["लरावेली", "laravel"],
  ["लरावेल", "laravel"],
  ["माइग्रेशन", "migration"],
  ["मुख्यमंत्री", "chief minister"],
  ["जन्माष्टमी", "janmashtami"],
  ["यूनिवर्सिटी", "university"],
  ["कॉउ", "cow"],
  ["मिल्क", "milk"],
  ["गिव्स", "gives"],
  ["खबर", "news"],
  ["खबरें", "news"],
  ["समाचार", "news"],
  ["ट्विटर", "twitter"],
  ["ट्वीट", "tweet"],
  ["न्यूज", "news"],
  ["हेडलाइन", "headline"],
  ["न्यूयॉर्क", "new york"],
  ["हैदराबाद", "hyderabad"],
  ["अहमदाबाद", "ahmedabad"],
  ["बैंगलोर", "bangalore"],
  ["बेंगलुरु", "bangalore"],
  ["वाराणसी", "varanasi"],
  ["कोलकाता", "kolkata"],
  ["लखनऊ", "lucknow"],
  ["गोपाल गंज", "gopalganj"],
  ["गोपालगंज", "gopalganj"],
  ["मोती हारी", "motihari"],
  ["मोतीहारी", "motihari"],
  ["मोतिहारी", "motihari"],
  ["गुरु ग्राम", "gurgaon"],
  ["गुरूग्राम", "gurgaon"],
  ["गुरुग्राम", "gurgaon"],
  ["लाल किला", "red fort"],
  ["लालकिला", "red fort"],
  ["हरियाणा", "haryana"],
  ["डिस्टेंस", "distance"],
  ["डिस्टेन्स", "distance"],
  ["हरसरू", "harsaru"],
  ["बिहार", "bihar"],
  ["पटना", "patna"],
  ["अमेरिका", "america"],
  ["ट्रांसलेशन", "translation"],
  ["ट्रांसलेट", "translate"],
  ["अनुवाद", "translation"],
  ["किलोमीटर", "km"],
  ["कितनी", "kitni"],
  ["कितना", "kitna"],
  ["चल रहा", "chal raha"],
  ["दिल्ली", "delhi"],
  ["मुंबई", "mumbai"],
  ["बम्बई", "mumbai"],
  ["सिवान", "siwan"],
  ["चेन्नई", "chennai"],
  ["जयपुर", "jaipur"],
  ["नोएडा", "noida"],
  ["पुणे", "pune"],
  ["हिसार", "hisar"],
  ["भारत", "india"],
  ["लंदन", "london"],
  ["टोक्यो", "tokyo"],
  ["अंग्रेजी", "english"],
  ["अंग्रेज़ी", "english"],
  ["इंग्लिश", "english"],
  ["इंगलिश", "english"],
  ["हिन्दी", "hindi"],
  ["हिंदी", "hindi"],
  ["बताओ", "batao"],
  ["नाम", "naam"],
  ["दूरी", "duri"],
  ["आजकल", "aajkal"],
  ["क्या", "kya"],
  ["व्हाट", "what"],
  ["टुडे", "today"],
  ["टाइम", "time"],
  ["हेलो", "hello"],
  ["हैलो", "hello"],
  ["डेट", "date"],
  ["इस", "is"],
  ["दूर", "door"],
  ["है", "hai"],
  ["में", "mein"],
  ["की", "ki"],
  ["के", "ke"],
  ["का", "ka"],
  ["को", "ko"],
  ["से", "se"],
  ["तक", "tak"],
  ["तो", "to"],
  ["टू", "to"],
  ["इन", "in"],
];

export function fold(text: string) {
  let out = ` ${String(text || "").trim()} `;
  const pairs = [...PAIRS].sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of pairs) {
    out = out.split(from).join(` ${to} `);
  }
  return out
    .toLowerCase()
    .replace(/[?.!,]/g, " ")
    .replace(/\s+/g, " ")
    .split(" ")
    .map((word) => (word === "द" || word === "d" ? "the" : word))
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}
